name: myapp
description: A new Flutter project.
version: 1.0.0+1

dependency_overrides:
  path_provider_android: 2.0.11

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  path_provider: any

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true